---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microservice-role
  namespace: microservice
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservice-rolebinding
  namespace: microservice
subjects:
  - kind: ServiceAccount
    name: microservice-sa
    namespace: microservice
roleRef:
  kind: Role
  name: microservice-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  namespace: microservice
  labels:
    app: microservice
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      serviceAccountName: microservice-sa  # Attach the ServiceAccount to the pod - Needs to match terraform k8s-microservice-deployment.tf
      containers:
        - name: microservice
          image: acrautomaticfortnight.azurecr.io/microservice:latest
          ports:
            - containerPort: 3000

          # Liveness Probe
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          # Readiness Probe
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3

          # Resource Limits
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: microservice
spec:
  selector:
    app: microservice
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 3000  # Container port
  type: ClusterIP
