---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservice-rolebinding
  namespace: microservice
subjects:
  - kind: ServiceAccount
    name: microservice-sa
    namespace: microservice
roleRef:
  kind: Role
  name: microservice-role
  apiGroup: rbac.authorization.k8s.io
